In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('residence.csv')

In [5]:
df.head()

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
0,2001-09,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
1,2002-03,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,3,0,Final
2,2005-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,5,0,Final
3,2005-04,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
4,2005-07,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final

In [10]:
df[df['estimate']>5]

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
35,2010-06,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,7,0,Final
74,2015-12,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,8,0,Final
91,2018-12,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,6,0,Final
109,2021-08,2022-12,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,23,0,Final
123,2001-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Africa and the Middle East,61,0,Final
...,...,...,...,...,...,...,...,...,...,...
324030,2023-05,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,25,2,Provisional
324031,2023-06,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,2,Provisional
324032,2023-07,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,24,3,Provisional
324033,2023-08,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,36,4,Provisional
324034,2023-09,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,3,Provisional

In [12]:
df[df['citizenship'] == "NZ"]

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
0,2001-09,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
1,2002-03,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,3,0,Final
2,2005-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,5,0,Final
3,2005-04,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
4,2005-07,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
...,...,...,...,...,...,...,...,...,...,...
45909,2023-02,2023-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,0,0,Provisional
45910,2023-03,2023-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,1,0,Provisional
45911,2023-06,2023-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,1,0,Provisional
45912,2023-07,2023-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,0,1,Provisional
45913,2023-08,2023-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,0,0,Provisional

In [13]:
#AND & ---BOTH COND NEED TO BE TRUE
#OR  | ---EITHER COND NEED IS TRUE

In [16]:
df[(df['estimate']>5) & (df['citizenship'] == "NZ")]

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
35,2010-06,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,7,0,Final
74,2015-12,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,8,0,Final
91,2018-12,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,6,0,Final
109,2021-08,2022-12,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,23,0,Final
123,2001-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Africa and the Middle East,61,0,Final
...,...,...,...,...,...,...,...,...,...,...
45815,2001-01,2020-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,7,0,Final
45831,2002-10,2020-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,6,0,Final
45833,2002-12,2020-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,7,0,Final
45836,2003-04,2020-09,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,6,0,Final
45902,2020-09,2022-01,Long-term migrant,Arrivals,NZ,TOTAL,Zimbabwe,7,0,Final

In [17]:
df[(df['estimate']>5) | (df['citizenship'] == "NZ")]

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
0,2001-09,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
1,2002-03,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,3,0,Final
2,2005-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,5,0,Final
3,2005-04,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
4,2005-07,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
...,...,...,...,...,...,...,...,...,...,...
324030,2023-05,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,25,2,Provisional
324031,2023-06,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,2,Provisional
324032,2023-07,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,24,3,Provisional
324033,2023-08,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,36,4,Provisional
324034,2023-09,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,3,Provisional

In [18]:
df.head()

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
0,2001-09,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
1,2002-03,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,3,0,Final
2,2005-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,5,0,Final
3,2005-04,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
4,2005-07,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final

In [21]:
df[(df['citizenship'] == "non-NZ") | (df['citizenship'] == "NZ")]

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
0,2001-09,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
1,2002-03,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,3,0,Final
2,2005-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,5,0,Final
3,2005-04,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
4,2005-07,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
...,...,...,...,...,...,...,...,...,...,...
324030,2023-05,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,25,2,Provisional
324031,2023-06,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,2,Provisional
324032,2023-07,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,24,3,Provisional
324033,2023-08,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,36,4,Provisional
324034,2023-09,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,3,Provisional

In [23]:
df[df['citizenship'].isin(['NZ','non-NZ'])]

,year_month,month_of_release,passenger_type,direction,citizenship,visa,country_of_residence,estimate,standard_error,status
0,2001-09,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
1,2002-03,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,3,0,Final
2,2005-01,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,5,0,Final
3,2005-04,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
4,2005-07,2020-09,Long-term migrant,Arrivals,NZ,NZ and Australian citizens,Afghanistan,1,0,Final
...,...,...,...,...,...,...,...,...,...,...
324030,2023-05,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,25,2,Provisional
324031,2023-06,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,2,Provisional
324032,2023-07,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,24,3,Provisional
324033,2023-08,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,36,4,Provisional
324034,2023-09,2023-09,Long-term migrant,Arrivals,non-NZ,Work,Zimbabwe,27,3,Provisional